import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Sparkles, Download, Plus, Loader2, Calendar, Shield, AlertTriangle, ChevronRight, Copy, CheckCheck } from 'lucide-react';
import { useStore } from '../hooks/useStore';
import { generateReport } from '../services/gemini';
import { format } from 'date-fns';
import toast from 'react-hot-toast';

const REPORT_TEMPLATES = [
  { id: 'daily', label: 'Daily Threat Summary', icon: AlertTriangle, color: 'rose', desc: 'All threats detected in last 24 hours with AI analysis.' },
  { id: 'weekly', label: 'Weekly Intelligence Brief', icon: FileText, color: 'indigo', desc: 'Aggregated weekly patterns and platform-level analysis.' },
  { id: 'takedown', label: 'Takedown Activity Report', icon: Shield, color: 'emerald', desc: 'Status of all DMCA notices, successes, and pending cases.' },
  { id: 'exec', label: 'Executive Summary', icon: Sparkles, color: 'violet', desc: 'High-level impact metrics for stakeholder presentations.' },
];

export default function Reports() {
  const { threats } = useStore();
  const [generating, setGenerating] = useState(false);
  const [activeTemplate, setActiveTemplate] = useState(null);
  const [reports, setReports] = useState([
    { id: 'r1', title: 'Weekly Intelligence Brief', createdAt: new Date(Date.now() - 2 * 86400000), status: 'ready', preview: 'High-risk activity detected across 4 platforms. Mumbai and Karachi identified as top origin regions. 3 DMCA notices dispatched...', threats: 12 },
    { id: 'r2', title: 'Takedown Activity Report', createdAt: new Date(Date.now() - 5 * 86400000), status: 'ready', preview: 'Total takedown requests this period: 9. Success rate: 89%. 1 case escalated to legal team for manual review...', threats: 9 },
  ]);
  const [activeReport, setActiveReport] = useState(null);
  const [reportContent, setReportContent] = useState('');
  const [copied, setCopied] = useState(false);

  const handleGenerate = async (template) => {
    setGenerating(true);
    setActiveTemplate(template.id);
    setActiveReport(null);
    try {
      const content = await generateReport(threats.filter(t => t.status !== 'safe').slice(0, 6));
      const newReport = {
        id: `r${Date.now()}`,
        title: template.label,
        createdAt: new Date(),
        status: 'ready',
        preview: content ? content.slice(0, 120) + '…' : 'AI report generated successfully.',
        threats: threats.filter(t => t.status !== 'safe').length,
        content,
      };
      setReports(prev => [newReport, ...prev]);
      setActiveReport(newReport);
      setReportContent(content || getFallbackReport(template, threats));
      toast.success('Report generated by Gemini');
    } catch {
      const content = getFallbackReport(template, threats);
      setReportContent(content);
      toast.success('Report generated');
    } finally {
      setGenerating(false);
      setActiveTemplate(null);
    }
  };

  const viewReport = (report) => {
    setActiveReport(report);
    setReportContent(report.content || getFallbackReport({ label: report.title }, threats));
  };

  const copy = () => {
    navigator.clipboard.writeText(reportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const colorMap = { rose: { bg: 'bg-rose-500/8', border: 'border-rose-500/20', icon: 'text-rose-400', badge: 'bg-rose-500/10 text-rose-300' },
    indigo: { bg: 'bg-indigo-500/8', border: 'border-indigo-500/20', icon: 'text-indigo-400', badge: 'bg-indigo-500/10 text-indigo-300' },
    emerald: { bg: 'bg-emerald-500/8', border: 'border-emerald-500/20', icon: 'text-emerald-400', badge: 'bg-emerald-500/10 text-emerald-300' },
    violet: { bg: 'bg-violet-500/8', border: 'border-violet-500/20', icon: 'text-violet-400', badge: 'bg-violet-500/10 text-violet-300' },
  };

  return (
    <div className="space-y-6">
      {/* Templates */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <div>
            <p className="section-label">GENERATE NEW REPORT</p>
            <p className="text-sm font-semibold text-aurora-text mt-1">AI-powered intelligence documentation</p>
          </div>
          <div className="flex items-center gap-1.5 text-xs font-mono text-aurora-muted">
            <Sparkles size={12} className="text-indigo-400" />
            Powered by Gemini 1.5 Flash
          </div>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {REPORT_TEMPLATES.map((t) => {
            const c = colorMap[t.color];
            const isLoading = generating && activeTemplate === t.id;
            return (
              <motion.button key={t.id} whileHover={{ y: -2 }} whileTap={{ scale: 0.98 }}
                onClick={() => !generating && handleGenerate(t)}
                className={`aurora-card p-4 text-left border ${c.border} ${c.bg} hover:border-opacity-60 transition-all duration-200 disabled:opacity-50`}
                disabled={generating}>
                <div className="flex items-start justify-between mb-3">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center"
                    style={{ background: 'rgba(99,102,241,0.1)', border: '1px solid rgba(99,102,241,0.15)' }}>
                    {isLoading ? <Loader2 size={16} className={`${c.icon} animate-spin`} /> : <t.icon size={16} className={c.icon} />}
                  </div>
                  <span className={`text-[10px] font-mono font-semibold px-2 py-0.5 rounded-full ${c.badge}`}>AI</span>
                </div>
                <p className="text-sm font-semibold text-aurora-text mb-1">{t.label}</p>
                <p className="text-xs text-aurora-muted leading-relaxed">{t.desc}</p>
              </motion.button>
            );
          })}
        </div>
      </div>

      <div className="grid lg:grid-cols-5 gap-5">
        {/* Report list */}
        <div className="lg:col-span-2 space-y-3">
          <p className="section-label">SAVED REPORTS</p>
          {reports.map((r, i) => (
            <motion.div key={r.id} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.08 }}
              onClick={() => viewReport(r)}
              className={`aurora-card p-4 cursor-pointer transition-all duration-200 hover:border-aurora-border-bright
                ${activeReport?.id === r.id ? 'border-indigo-500/30 bg-indigo-500/5' : ''}`}>
              <div className="flex items-start justify-between gap-2 mb-2">
                <p className="text-sm font-semibold text-aurora-text">{r.title}</p>
                <ChevronRight size={14} className="text-aurora-muted flex-shrink-0 mt-0.5" />
              </div>
              <p className="text-xs text-aurora-muted line-clamp-2 leading-relaxed mb-2">{r.preview}</p>
              <div className="flex items-center gap-3 text-[11px] font-mono text-aurora-muted">
                <span className="flex items-center gap-1"><Calendar size={10} /> {format(r.createdAt, 'dd MMM yyyy')}</span>
                <span className="flex items-center gap-1"><AlertTriangle size={10} /> {r.threats} threats</span>
              </div>
            </motion.div>
          ))}

          {reports.length === 0 && (
            <div className="aurora-card p-8 text-center">
              <FileText size={24} className="text-aurora-muted mx-auto mb-2 opacity-40" />
              <p className="text-sm text-aurora-muted">No reports yet. Generate your first one above.</p>
            </div>
          )}
        </div>

        {/* Report viewer */}
        <div className="lg:col-span-3">
          <AnimatePresence mode="wait">
            {activeReport && reportContent ? (
              <motion.div key={activeReport.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
                className="aurora-card p-5 h-full">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <p className="font-display font-bold text-aurora-text">{activeReport.title}</p>
                    <p className="text-xs text-aurora-muted font-mono mt-0.5">
                      Generated {format(activeReport.createdAt, 'dd MMM yyyy, HH:mm')} · Gemini AI
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <button onClick={copy} className="btn-secondary text-xs py-2 px-3 flex items-center gap-1.5">
                      {copied ? <><CheckCheck size={12} className="text-emerald-400" /> Copied</> : <><Copy size={12} /> Copy</>}
                    </button>
                    <button className="btn-primary text-xs py-2 px-3 flex items-center gap-1.5">
                      <Download size={12} /> Export PDF
                    </button>
                  </div>
                </div>
                <div className="h-px bg-aurora-border mb-4" />
                <div className="overflow-y-auto" style={{ maxHeight: 480 }}>
                  <pre className="text-sm text-aurora-text font-body whitespace-pre-wrap leading-relaxed">{reportContent}</pre>
                </div>
              </motion.div>
            ) : (
              <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                className="aurora-card p-12 text-center h-full flex flex-col items-center justify-center gap-3">
                <div className="w-14 h-14 rounded-2xl flex items-center justify-center"
                  style={{ background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.15)' }}>
                  <FileText size={24} className="text-indigo-400 opacity-60" />
                </div>
                <p className="font-semibold text-aurora-text">No report selected</p>
                <p className="text-sm text-aurora-muted max-w-xs">Generate a new report using the templates above, or select a saved report to view it here.</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}

function getFallbackReport(template, threats) {
  const unauthorized = threats.filter(t => t.status === 'unauthorized');
  const suspicious = threats.filter(t => t.status === 'suspicious');
  return `${template.label?.toUpperCase() || 'THREAT INTELLIGENCE REPORT'}
Generated by Sentinel-Media AI · ${format(new Date(), 'dd MMMM yyyy, HH:mm')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY
─────────────────
Sentinel-Media detected ${threats.length} total incidents across monitored asset streams in this reporting period. Of these, ${unauthorized.length} were classified as unauthorized redistribution requiring immediate action, and ${suspicious.length} were flagged as suspicious for manual review.

KEY FINDINGS
────────────
• ${unauthorized.length} confirmed unauthorized media redistributions detected
• Top risk regions: India (${threats.filter(t=>t.location==='India').length} incidents), Pakistan (${threats.filter(t=>t.location==='Pakistan').length} incidents)
• Estimated unauthorized audience reach: ${(threats.reduce((s,t)=>s+(t.views||0),0)/1000).toFixed(0)}K views
• Most active unauthorized platform: Telegram, Facebook
• Average detection confidence score: ${Math.round(threats.reduce((s,t)=>s+t.confidence,0)/Math.max(threats.length,1))}%

RISK ASSESSMENT
───────────────
HIGH PRIORITY: ${unauthorized.length} assets require immediate DMCA takedown action.
The detected violations show patterns consistent with organized piracy operations, including systematic watermark removal and coordinated cross-platform redistribution.

RECOMMENDED ACTIONS
───────────────────
1. Dispatch DMCA takedown notices to all ${unauthorized.length} flagged platforms immediately
2. Escalate high-confidence cases (>90%) to legal team for further proceedings
3. Enhance fingerprint database with latest broadcast segments
4. Expand monitoring coverage to VK, Dailymotion, and regional streaming platforms
5. Consider blockchain-based timestamp registration for upcoming match broadcasts

METHODOLOGY
───────────
Detection powered by perceptual hashing (pHash), CLIP semantic embeddings, and Google Gemini 1.5 Flash AI classification. Similarity threshold: 60%+ for review, 85%+ for automated flagging.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Sentinel-Media · AI Digital Asset Guardian · Confidential`;
}
